![Title](Images/cisco.png)

# Lab - Internet Meter Data Analysis

### Objectives
<li>**Part 1: Collect and Store Data**</li>
<li>**Part 2: Manipulate Data**</li>
### Scenario/Background
In this lab, you will acquire Internet speed statistics and store the live data in a comma separated values (csv) file. You will also load the stored data from the csv file to a Python data structure, the Pandas `DataFrame`, and use its functionalities to explore the data and manipulate it so that it is easily readable.
### Required Resources
* 1 PC with Internet access
* Raspberry Pi version 2 or higher
* Python libraries: datetime, csv, subprocess, pandas, numpy
* Datafiles: rpi_data_long.csv

## Part 1: Collect and Store Data
<p>The goal of this first part of the lab is to gather internet speed measurements through the Raspberry Pi. Three kinds of measurements will be collected:
1. Ping speed
2. Download speed
3. Upload speed

#### Step 1: Install Speedtest and Import Python Libraries.
In this step, you will install Speedtest and import Python libraries.
<p>Speedtest-cli is a Python script that measures the upload and download speed of your Internet connection. For more information about speedtest, go to https://github.com/sivel/speedtest-cli.

a) Install `speedtest-cli`.

In [1]:
# Code cell 1
!pip install speedtest-cli

Collecting speedtest-cli
  Downloading speedtest_cli-2.1.3-py2.py3-none-any.whl.metadata (6.8 kB)
Downloading speedtest_cli-2.1.3-py2.py3-none-any.whl (23 kB)
Installing collected packages: speedtest-cli
Successfully installed speedtest-cli-2.1.3

This cli allows the Jupyter notebook to connect to the website and store the data.

b) Import the necessary Python libraries.

In [2]:
# Code cell 2
# Python library to manage date and time data
import datetime
# Python library to read and write csv files
import csv
# Python library to execute bash commands from the notebook.
# If you want to know more about this, check this resource:
# http://www.pythonforbeginners.com/os/subprocess-for-system-administrators
import subprocess

#### Step 2: Generate timestamps using the `datetime` package.
In this lab, measurements of Internet speed statistics will be generated. A crucial step in data acquisition for the majority of data analytics applications, is to associate a timestamp to measurements.

a) To generate a timestamp, use the `datetime.now` function of the `datetime` package:

In [3]:
# Code cell 3
date_time = datetime.datetime.now()
print(date_time, type(date_time))

2026-02-17 08:06:27.240361 <class 'datetime.datetime'>

b) An instance of the class `datetime` cannot be directly written to in text form. The function `strftime` parses the date information into a string. The arguments of this function determine the format of the output sting. A description of these parameters can be found in the documentation of the `strftime` function at https://docs.python.org/2/library/time.html.

In [4]:
# Code cell 4
date_time.strftime('%a, %d %b %Y %H:%M:%S')

'Tue, 17 Feb 2026 08:06:27'

After reading the documentation of the `strftime` function, generate a timestamp and parse it into a string with the following format: YYYY-MM-DD HH:MM:SS.

In [7]:
# Code cell 5
date_time = datetime.datetime.now()
date_time.strftime("%Y-%m-%d %H:%M:%S")
print(date_time)

2026-02-17 08:09:57.237985

#### Step 3: Run the process and collect the output with Python.

The `speedtest-cli` command, if run from a terminal, returns a string with download and upload speeds. To run the command from this notebook, it is necessary to use the Python module `subprocess`, which allows running a process directly from the notebook code cell.

a) Run a speed test using the `speedtest-cli` command from Python. The output will be stored in the process_output variable.

In [8]:
# Code cell 6
# This string contains the command line to interface with speedtest.net
speedtest_cmd = "speedtest-cli --simple"
# Execute the process
process = subprocess.Popen(speedtest_cmd.split(), stdout=subprocess.PIPE)
# Collect the command output
process_output = process.communicate()[0]

b) Print the process output. Notice the type for the `process_output` variable.

In [9]:
# Code cell 7
print(process_output, type(process_output))

b'Ping: 21.996 ms\nDownload: 3410.48 Mbit/s\nUpload: 602.72 Mbit/s\n' <class 'bytes'>

c) The speed test result is split, and a timestamp is appended to the results.

In [10]:
# Code cell 8
# Store the time at which the speedtest was executed
date_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
process_output = process_output.split()
process_output.append(date_time)
print(process_output, type(process_output))

[b'Ping:', b'21.996', b'ms', b'Download:', b'3410.48', b'Mbit/s', b'Upload:', b'602.72', b'Mbit/s', '2026-02-17 08:10:30'] <class 'list'>

d) The speedtest() function is created to return the results from the speedtest-cli command.

In [25]:
# Code cell 9
# function to excute the speed test
def speedtest():
    # We need to store the time at which the speedtest was executed
    date_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # This is a string that contains what we would write on the command line
    #to interface with speedtest.net
    speedtest_cmd = "speedtest-cli --simple"
    # We now execute the process:
    process = subprocess.Popen(speedtest_cmd.split(), stdout=subprocess.PIPE)
    process_output = process.communicate()[0]
    process_output = process_output.split()
    # and we add the date and time
    process_output.append(date_time)
    return process_output

What does the speedtest() function return? What is the code to view results from the speedtest() function?

Функция `speedtest()` возвращает список, содержащий результаты измерения скорости (ping, скорость загрузки, скорость выгрузки) и метку времени, когда был выполнен тест.

Для просмотра результатов можно вызвать функцию и распечатать её вывод с помощью `print`

In [26]:
# Code cell 10
print(speedtest())

[b'Ping:', b'14.13', b'ms', b'Download:', b'2140.57', b'Mbit/s', b'Upload:', b'704.05', b'Mbit/s', '2026-02-17 08:30:59']

#### Step 4: Store the output of the `speedtest()` function.

The comma separated values (csv) is the most common import and export format for spreadsheets and databases. To learn more information about working with csv in Python, navigate to https://docs.python.org/2/library/csv.html.

a) Create a file named test.txt in the /tmp directory and write "test_msg" in the file.

In [14]:
# Code cell 11
with open("/tmp/test.txt",'w') as f:
    f.write('test_msg')

b) Use the Linux command `cat` to verify the creation and content of the file.

In [15]:
# Code cell 12
!cat /tmp/test.txt

test_msg

c) To check that the file was successfully open:

In [16]:
# Code cell 13
with open("/tmp/test.txt",'r') as f:
   str = f.read()
print(str)

test_msg

d) Understanding the meaning of the `with` statement, especially in combination with `try` and `except` is not required for the rest of this lab, but a useful resource about this is http://effbot.org/zone/python-with-statement.htm.
<p>
To write into a `csv` file, it is necessary to create a `csv.writer` object. Check https://docs.python.org/2/library/csv.html and find out which function of the 'csv.writer' object can be used to add a row to a `csv` file.

In [27]:
# Code cell 14
# function to save data to csv
def save_to_csv(data, filename):
    try:
        # If the file exists, we want to append a new line to it, with the
        #results of the current experiment
        with open(filename + '.csv', 'a') as f:
            wr = csv.writer(f)
            wr.writerow(data)
    except:
        # If it does not exist, create the file first
        with open(filename + '.csv', 'w') as f:
            # Hint: This is similar to appending new lines to a file.
            # Create a csv writer object
            wr = csv.writer(f)
            # Save (write) to file
            wr.writerow(data)

#### Step 5: Check the collected data.
Write a function to open a csv file and print its content to screen. You can find an example in the 13.1.5 section of https://docs.python.org/2/library/csv.html

In [19]:
# Code cell 15
def print_from_csv(filename):
    with open(filename + '.csv', 'r') as f:
            re = csv.reader(f)
            # 1. Loop over the rows
            for row in re:
              # 2. print
              print(row)

Now, all the functions needed to collect and store Internet speed data are finished.
#### Step 6: Run the Speedtest multiple times and store the data.
a) Write a `for` loop that calls the speedtest 5 times, prints the output of the tests, and stores the data in a csv file.

In [20]:
# Code cell 16
for i in range(5):
    speedtest_output = speedtest()
    print('Test number {}'.format(i))
    print(speedtest_output)
    save_to_csv(speedtest_output, '/tmp/rpi_data_test')

Test number 0
[b'Ping:', b'17.49', b'ms', b'Download:', b'2293.71', b'Mbit/s', b'Upload:', b'566.05', b'Mbit/s', '2026-02-17 08:18:19']
Test number 1
[b'Ping:', b'13.438', b'ms', b'Download:', b'2391.84', b'Mbit/s', b'Upload:', b'670.04', b'Mbit/s', '2026-02-17 08:18:24']
Test number 2
[b'Ping:', b'13.088', b'ms', b'Download:', b'3771.95', b'Mbit/s', b'Upload:', b'676.25', b'Mbit/s', '2026-02-17 08:18:28']
Test number 3
[b'Ping:', b'13.008', b'ms', b'Download:', b'2329.24', b'Mbit/s', b'Upload:', b'646.18', b'Mbit/s', '2026-02-17 08:18:33']
Test number 4
[b'Ping:', b'13.049', b'ms', b'Download:', b'2332.00', b'Mbit/s', b'Upload:', b'545.32', b'Mbit/s', '2026-02-17 08:18:37']

b) Display the file to verify that the data has been saved correctly.

In [21]:
# Code cell 17
print_from_csv('/tmp/rpi_data_test')

["b'Ping:'", "b'17.49'", "b'ms'", "b'Download:'", "b'2293.71'", "b'Mbit/s'", "b'Upload:'", "b'566.05'", "b'Mbit/s'", '2026-02-17 08:18:19']
["b'Ping:'", "b'13.438'", "b'ms'", "b'Download:'", "b'2391.84'", "b'Mbit/s'", "b'Upload:'", "b'670.04'", "b'Mbit/s'", '2026-02-17 08:18:24']
["b'Ping:'", "b'13.088'", "b'ms'", "b'Download:'", "b'3771.95'", "b'Mbit/s'", "b'Upload:'", "b'676.25'", "b'Mbit/s'", '2026-02-17 08:18:28']
["b'Ping:'", "b'13.008'", "b'ms'", "b'Download:'", "b'2329.24'", "b'Mbit/s'", "b'Upload:'", "b'646.18'", "b'Mbit/s'", '2026-02-17 08:18:33']
["b'Ping:'", "b'13.049'", "b'ms'", "b'Download:'", "b'2332.00'", "b'Mbit/s'", "b'Upload:'", "b'545.32'", "b'Mbit/s'", '2026-02-17 08:18:37']

If a bigger dataset is needed, the speedtest can be running in the background for more samples.

How would you change the code if you wanted to run the code 100 times?

Поменяю значение range на нужное мне количество, например `range(100)`

In [28]:
# Code cell 18
# Code to run 100 times
for i in range(100):
    speedtest_output = speedtest()
    print('Test number: {}'.format(i))
    print(speedtest_output)
    save_to_csv(speedtest_output, '/tmp/rpi_data')

Test number: 0
[b'Ping:', b'13.153', b'ms', b'Download:', b'2364.96', b'Mbit/s', b'Upload:', b'683.74', b'Mbit/s', '2026-02-17 08:31:18']
Test number: 1
[b'Ping:', b'13.156', b'ms', b'Download:', b'2225.70', b'Mbit/s', b'Upload:', b'649.08', b'Mbit/s', '2026-02-17 08:31:22']
Test number: 2
[b'Ping:', b'13.073', b'ms', b'Download:', b'3098.24', b'Mbit/s', b'Upload:', b'648.54', b'Mbit/s', '2026-02-17 08:31:27']
Test number: 3
[b'Ping:', b'17.291', b'ms', b'Download:', b'2292.59', b'Mbit/s', b'Upload:', b'576.87', b'Mbit/s', '2026-02-17 08:31:31']
Test number: 4
[b'Ping:', b'13.124', b'ms', b'Download:', b'2392.33', b'Mbit/s', b'Upload:', b'655.64', b'Mbit/s', '2026-02-17 08:31:36']
Test number: 5
[b'Ping:', b'13.204', b'ms', b'Download:', b'2157.15', b'Mbit/s', b'Upload:', b'622.49', b'Mbit/s', '2026-02-17 08:31:41']
Test number: 6
[b'Ping:', b'13.2', b'ms', b'Download:', b'2272.66', b'Mbit/s', b'Upload:', b'644.90', b'Mbit/s', '2026-02-17 08:31:46']
Test number: 7
[b'Ping:', b'13.058', b'ms', b'Download:', b'3186.89', b'Mbit/s', b'Upload:', b'618.09', b'Mbit/s', '2026-02-17 08:31:50']
Test number: 8
[b'Ping:', b'13.15', b'ms', b'Download:', b'2286.55', b'Mbit/s', b'Upload:', b'664.56', b'Mbit/s', '2026-02-17 08:31:55']
Test number: 9
[b'Ping:', b'13.247', b'ms', b'Download:', b'2329.26', b'Mbit/s', b'Upload:', b'616.61', b'Mbit/s', '2026-02-17 08:31:59']
Test number: 10
[b'Ping:', b'13.422', b'ms', b'Download:', b'3305.65', b'Mbit/s', b'Upload:', b'527.71', b'Mbit/s', '2026-02-17 08:32:04']
Test number: 11
[b'Ping:', b'13.822', b'ms', b'Download:', b'2377.78', b'Mbit/s', b'Upload:', b'682.40', b'Mbit/s', '2026-02-17 08:32:09']
Test number: 12
[b'Ping:', b'14.201', b'ms', b'Download:', b'2465.96', b'Mbit/s', b'Upload:', b'676.34', b'Mbit/s', '2026-02-17 08:32:13']
Test number: 13
[b'Ping:', b'13.807', b'ms', b'Download:', b'3295.50', b'Mbit/s', b'Upload:', b'580.35', b'Mbit/s', '2026-02-17 08:32:18']
Test number: 14
[b'Ping:', b'14.066', b'ms', b'Download:', b'2310.94', b'Mbit/s', b'Upload:', b'576.96', b'Mbit/s', '2026-02-17 08:32:22']
Test number: 15
[b'Ping:', b'13.52', b'ms', b'Download:', b'2307.93', b'Mbit/s', b'Upload:', b'717.55', b'Mbit/s', '2026-02-17 08:32:27']
Test number: 16
[b'Ping:', b'17.275', b'ms', b'Download:', b'3147.50', b'Mbit/s', b'Upload:', b'666.15', b'Mbit/s', '2026-02-17 08:32:32']
Test number: 17
[b'Ping:', b'14.009', b'ms', b'Download:', b'2263.08', b'Mbit/s', b'Upload:', b'670.85', b'Mbit/s', '2026-02-17 08:32:36']
Test number: 18
[b'Ping:', b'13.6', b'ms', b'Download:', b'2289.17', b'Mbit/s', b'Upload:', b'642.98', b'Mbit/s', '2026-02-17 08:32:41']
Test number: 19
[b'Ping:', b'13.417', b'ms', b'Download:', b'2360.38', b'Mbit/s', b'Upload:', b'614.25', b'Mbit/s', '2026-02-17 08:32:45']
Test number: 20
[b'Ping:', b'13.58', b'ms', b'Download:', b'2371.59', b'Mbit/s', b'Upload:', b'588.81', b'Mbit/s', '2026-02-17 08:32:50']
Test number: 21
[b'Ping:', b'13.47', b'ms', b'Download:', b'2688.18', b'Mbit/s', b'Upload:', b'593.49', b'Mbit/s', '2026-02-17 08:32:55']
Test number: 22
[b'Ping:', b'13.762', b'ms', b'Download:', b'2210.32', b'Mbit/s', b'Upload:', b'559.12', b'Mbit/s', '2026-02-17 08:32:59']
Test number: 23
[b'Ping:', b'13.692', b'ms', b'Download:', b'2246.38', b'Mbit/s', b'Upload:', b'634.99', b'Mbit/s', '2026-02-17 08:33:04']
Test number: 24
[b'Ping:', b'13.764', b'ms', b'Download:', b'3429.51', b'Mbit/s', b'Upload:', b'528.60', b'Mbit/s', '2026-02-17 08:33:09']
Test number: 25
[b'Ping:', b'13.776', b'ms', b'Download:', b'2366.37', b'Mbit/s', b'Upload:', b'567.92', b'Mbit/s', '2026-02-17 08:33:14']
Test number: 26
[b'Ping:', b'13.708', b'ms', b'Download:', b'2311.80', b'Mbit/s', b'Upload:', b'674.44', b'Mbit/s', '2026-02-17 08:33:19']
Test number: 27
[b'Ping:', b'13.72', b'ms', b'Download:', b'3282.53', b'Mbit/s', b'Upload:', b'596.21', b'Mbit/s', '2026-02-17 08:33:23']
Test number: 28
[b'Ping:', b'14.118', b'ms', b'Download:', b'2269.25', b'Mbit/s', b'Upload:', b'687.89', b'Mbit/s', '2026-02-17 08:33:28']
Test number: 29
[b'Ping:', b'13.543', b'ms', b'Download:', b'2144.25', b'Mbit/s', b'Upload:', b'566.26', b'Mbit/s', '2026-02-17 08:33:32']
Test number: 30
[b'Ping:', b'13.942', b'ms', b'Download:', b'2394.48', b'Mbit/s', b'Upload:', b'682.69', b'Mbit/s', '2026-02-17 08:33:37']
Test number: 31
[b'Ping:', b'13.741', b'ms', b'Download:', b'2360.91', b'Mbit/s', b'Upload:', b'642.43', b'Mbit/s', '2026-02-17 08:33:42']
Test number: 32
[b'Ping:', b'13.349', b'ms', b'Download:', b'2469.34', b'Mbit/s', b'Upload:', b'563.91', b'Mbit/s', '2026-02-17 08:33:47']
Test number: 33
[b'Ping:', b'13.603', b'ms', b'Download:', b'2322.02', b'Mbit/s', b'Upload:', b'631.81', b'Mbit/s', '2026-02-17 08:33:52']
Test number: 34
[b'Ping:', b'13.655', b'ms', b'Download:', b'2134.16', b'Mbit/s', b'Upload:', b'674.89', b'Mbit/s', '2026-02-17 08:33:56']
Test number: 35
[b'Ping:', b'14.555', b'ms', b'Download:', b'3091.86', b'Mbit/s', b'Upload:', b'560.14', b'Mbit/s', '2026-02-17 08:34:01']
Test number: 36
[b'Ping:', b'13.563', b'ms', b'Download:', b'2159.27', b'Mbit/s', b'Upload:', b'591.23', b'Mbit/s', '2026-02-17 08:34:06']
Test number: 37
[b'Ping:', b'13.65', b'ms', b'Download:', b'2187.89', b'Mbit/s', b'Upload:', b'719.99', b'Mbit/s', '2026-02-17 08:34:11']
Test number: 38
[b'Ping:', b'13.755', b'ms', b'Download:', b'3167.76', b'Mbit/s', b'Upload:', b'667.80', b'Mbit/s', '2026-02-17 08:34:15']
Test number: 39
[b'Ping:', b'13.76', b'ms', b'Download:', b'2306.74', b'Mbit/s', b'Upload:', b'667.57', b'Mbit/s', '2026-02-17 08:34:19']
Test number: 40
[b'Ping:', b'13.539', b'ms', b'Download:', b'2215.29', b'Mbit/s', b'Upload:', b'630.99', b'Mbit/s', '2026-02-17 08:34:24']
Test number: 41
[b'Ping:', b'14.214', b'ms', b'Download:', b'3230.99', b'Mbit/s', b'Upload:', b'645.52', b'Mbit/s', '2026-02-17 08:34:29']
Test number: 42
[b'Ping:', b'13.595', b'ms', b'Download:', b'2367.31', b'Mbit/s', b'Upload:', b'646.61', b'Mbit/s', '2026-02-17 08:34:33']
Test number: 43
[b'Ping:', b'13.632', b'ms', b'Download:', b'2287.06', b'Mbit/s', b'Upload:', b'625.75', b'Mbit/s', '2026-02-17 08:34:38']
Test number: 44
[b'Ping:', b'13.897', b'ms', b'Download:', b'3102.35', b'Mbit/s', b'Upload:', b'690.33', b'Mbit/s', '2026-02-17 08:34:43']
Test number: 45
[b'Ping:', b'13.575', b'ms', b'Download:', b'2355.62', b'Mbit/s', b'Upload:', b'650.59', b'Mbit/s', '2026-02-17 08:34:47']
Test number: 46
[b'Ping:', b'13.796', b'ms', b'Download:', b'2216.15', b'Mbit/s', b'Upload:', b'644.30', b'Mbit/s', '2026-02-17 08:34:52']
Test number: 47
[b'Ping:', b'13.833', b'ms', b'Download:', b'2307.40', b'Mbit/s', b'Upload:', b'688.86', b'Mbit/s', '2026-02-17 08:34:56']
Test number: 48
[b'Ping:', b'13.782', b'ms', b'Download:', b'2293.59', b'Mbit/s', b'Upload:', b'657.68', b'Mbit/s', '2026-02-17 08:35:01']
Test number: 49
[b'Ping:', b'13.884', b'ms', b'Download:', b'2576.54', b'Mbit/s', b'Upload:', b'597.63', b'Mbit/s', '2026-02-17 08:35:06']
Test number: 50
[b'Ping:', b'13.751', b'ms', b'Download:', b'2128.05', b'Mbit/s', b'Upload:', b'565.44', b'Mbit/s', '2026-02-17 08:35:10']
Test number: 51
[b'Ping:', b'13.774', b'ms', b'Download:', b'2270.09', b'Mbit/s', b'Upload:', b'624.26', b'Mbit/s', '2026-02-17 08:35:15']
Test number: 52
[b'Ping:', b'13.856', b'ms', b'Download:', b'3408.27', b'Mbit/s', b'Upload:', b'688.87', b'Mbit/s', '2026-02-17 08:35:20']
Test number: 53
[b'Ping:', b'13.998', b'ms', b'Download:', b'2383.23', b'Mbit/s', b'Upload:', b'517.80', b'Mbit/s', '2026-02-17 08:35:24']
Test number: 54
[b'Ping:', b'14.084', b'ms', b'Download:', b'2274.59', b'Mbit/s', b'Upload:', b'577.76', b'Mbit/s', '2026-02-17 08:35:29']
Test number: 55
[b'Ping:', b'13.67', b'ms', b'Download:', b'3339.34', b'Mbit/s', b'Upload:', b'546.55', b'Mbit/s', '2026-02-17 08:35:34']
Test number: 56
[b'Ping:', b'13.774', b'ms', b'Download:', b'2087.49', b'Mbit/s', b'Upload:', b'708.27', b'Mbit/s', '2026-02-17 08:35:39']
Test number: 57
[b'Ping:', b'13.892', b'ms', b'Download:', b'2265.79', b'Mbit/s', b'Upload:', b'689.15', b'Mbit/s', '2026-02-17 08:35:44']
Test number: 58
[b'Ping:', b'13.9', b'ms', b'Download:', b'2751.45', b'Mbit/s', b'Upload:', b'660.16', b'Mbit/s', '2026-02-17 08:35:48']
Test number: 59
[b'Ping:', b'13.696', b'ms', b'Download:', b'2284.64', b'Mbit/s', b'Upload:', b'591.71', b'Mbit/s', '2026-02-17 08:35:53']
Test number: 60
[b'Ping:', b'13.683', b'ms', b'Download:', b'2298.04', b'Mbit/s', b'Upload:', b'708.11', b'Mbit/s', '2026-02-17 08:35:58']
Test number: 61
[b'Ping:', b'13.543', b'ms', b'Download:', b'2375.90', b'Mbit/s', b'Upload:', b'516.04', b'Mbit/s', '2026-02-17 08:36:02']
Test number: 62
[b'Ping:', b'13.538', b'ms', b'Download:', b'2382.80', b'Mbit/s', b'Upload:', b'633.11', b'Mbit/s', '2026-02-17 08:36:08']
Test number: 63
[b'Ping:', b'13.688', b'ms', b'Download:', b'3385.97', b'Mbit/s', b'Upload:', b'569.42', b'Mbit/s', '2026-02-17 08:36:12']
Test number: 64
[b'Ping:', b'14.07', b'ms', b'Download:', b'2282.86', b'Mbit/s', b'Upload:', b'672.47', b'Mbit/s', '2026-02-17 08:36:17']
Test number: 65
[b'Ping:', b'14.382', b'ms', b'Download:', b'2399.94', b'Mbit/s', b'Upload:', b'546.63', b'Mbit/s', '2026-02-17 08:36:22']
Test number: 66
[b'Ping:', b'13.93', b'ms', b'Download:', b'3396.11', b'Mbit/s', b'Upload:', b'708.69', b'Mbit/s', '2026-02-17 08:36:26']
Test number: 67
[b'Ping:', b'13.723', b'ms', b'Download:', b'2318.86', b'Mbit/s', b'Upload:', b'499.78', b'Mbit/s', '2026-02-17 08:36:31']
Test number: 68
[b'Ping:', b'13.644', b'ms', b'Download:', b'2409.85', b'Mbit/s', b'Upload:', b'640.02', b'Mbit/s', '2026-02-17 08:36:36']
Test number: 69
[b'Ping:', b'14.23', b'ms', b'Download:', b'3120.05', b'Mbit/s', b'Upload:', b'625.23', b'Mbit/s', '2026-02-17 08:36:41']
Test number: 70
[b'Ping:', b'14.174', b'ms', b'Download:', b'2457.06', b'Mbit/s', b'Upload:', b'544.86', b'Mbit/s', '2026-02-17 08:36:45']
Test number: 71
[b'Ping:', b'14.099', b'ms', b'Download:', b'2185.81', b'Mbit/s', b'Upload:', b'757.33', b'Mbit/s', '2026-02-17 08:36:50']
Test number: 72
[b'Ping:', b'14.136', b'ms', b'Download:', b'2434.40', b'Mbit/s', b'Upload:', b'674.00', b'Mbit/s', '2026-02-17 08:36:54']
Test number: 73
[b'Ping:', b'13.491', b'ms', b'Download:', b'2294.84', b'Mbit/s', b'Upload:', b'662.41', b'Mbit/s', '2026-02-17 08:36:59']
Test number: 74
[b'Ping:', b'13.663', b'ms', b'Download:', b'2421.61', b'Mbit/s', b'Upload:', b'516.74', b'Mbit/s', '2026-02-17 08:37:04']
Test number: 75
[b'Ping:', b'13.686', b'ms', b'Download:', b'2253.73', b'Mbit/s', b'Upload:', b'510.75', b'Mbit/s', '2026-02-17 08:37:09']
Test number: 76
[b'Ping:', b'13.678', b'ms', b'Download:', b'2287.98', b'Mbit/s', b'Upload:', b'575.92', b'Mbit/s', '2026-02-17 08:37:14']
Test number: 77
[b'Ping:', b'13.922', b'ms', b'Download:', b'3222.77', b'Mbit/s', b'Upload:', b'612.38', b'Mbit/s', '2026-02-17 08:37:19']
Test number: 78
[b'Ping:', b'13.704', b'ms', b'Download:', b'2392.13', b'Mbit/s', b'Upload:', b'619.35', b'Mbit/s', '2026-02-17 08:37:23']
Test number: 79
[b'Ping:', b'13.5', b'ms', b'Download:', b'2264.34', b'Mbit/s', b'Upload:', b'635.28', b'Mbit/s', '2026-02-17 08:37:28']
Test number: 80
[b'Ping:', b'13.858', b'ms', b'Download:', b'3109.64', b'Mbit/s', b'Upload:', b'707.46', b'Mbit/s', '2026-02-17 08:37:33']
Test number: 81
[b'Ping:', b'14.068', b'ms', b'Download:', b'2370.37', b'Mbit/s', b'Upload:', b'683.76', b'Mbit/s', '2026-02-17 08:37:37']
Test number: 82
[b'Ping:', b'13.735', b'ms', b'Download:', b'2408.31', b'Mbit/s', b'Upload:', b'641.94', b'Mbit/s', '2026-02-17 08:37:42']
Test number: 83
[b'Ping:', b'13.702', b'ms', b'Download:', b'3276.74', b'Mbit/s', b'Upload:', b'640.04', b'Mbit/s', '2026-02-17 08:37:46']
Test number: 84
[b'Ping:', b'13.872', b'ms', b'Download:', b'2309.64', b'Mbit/s', b'Upload:', b'642.42', b'Mbit/s', '2026-02-17 08:37:51']
Test number: 85
[b'Ping:', b'13.836', b'ms', b'Download:', b'2460.42', b'Mbit/s', b'Upload:', b'681.68', b'Mbit/s', '2026-02-17 08:37:55']
Test number: 86
[b'Ping:', b'13.661', b'ms', b'Download:', b'2470.32', b'Mbit/s', b'Upload:', b'584.04', b'Mbit/s', '2026-02-17 08:38:00']
Test number: 87
[b'Ping:', b'14.049', b'ms', b'Download:', b'2168.36', b'Mbit/s', b'Upload:', b'689.08', b'Mbit/s', '2026-02-17 08:38:05']
Test number: 88
[b'Ping:', b'13.7', b'ms', b'Download:', b'2538.57', b'Mbit/s', b'Upload:', b'610.42', b'Mbit/s', '2026-02-17 08:38:10']
Test number: 89
[b'Ping:', b'13.702', b'ms', b'Download:', b'2208.70', b'Mbit/s', b'Upload:', b'642.06', b'Mbit/s', '2026-02-17 08:38:14']
Test number: 90
[b'Ping:', b'13.633', b'ms', b'Download:', b'2261.72', b'Mbit/s', b'Upload:', b'577.12', b'Mbit/s', '2026-02-17 08:38:19']
Test number: 91
[b'Ping:', b'13.992', b'ms', b'Download:', b'3359.51', b'Mbit/s', b'Upload:', b'614.57', b'Mbit/s', '2026-02-17 08:38:24']
Test number: 92
[b'Ping:', b'14.193', b'ms', b'Download:', b'2216.16', b'Mbit/s', b'Upload:', b'637.55', b'Mbit/s', '2026-02-17 08:38:28']
Test number: 93
[b'Ping:', b'13.931', b'ms', b'Download:', b'2269.21', b'Mbit/s', b'Upload:', b'620.60', b'Mbit/s', '2026-02-17 08:38:33']
Test number: 94
[b'Ping:', b'14.373', b'ms', b'Download:', b'3238.93', b'Mbit/s', b'Upload:', b'653.77', b'Mbit/s', '2026-02-17 08:38:38']
Test number: 95
[b'Ping:', b'13.73', b'ms', b'Download:', b'2167.07', b'Mbit/s', b'Upload:', b'593.39', b'Mbit/s', '2026-02-17 08:38:42']
Test number: 96
[b'Ping:', b'13.729', b'ms', b'Download:', b'2372.47', b'Mbit/s', b'Upload:', b'605.76', b'Mbit/s', '2026-02-17 08:38:47']
Test number: 97
[b'Ping:', b'13.534', b'ms', b'Download:', b'3165.20', b'Mbit/s', b'Upload:', b'634.82', b'Mbit/s', '2026-02-17 08:38:52']
Test number: 98
[b'Ping:', b'13.654', b'ms', b'Download:', b'2226.01', b'Mbit/s', b'Upload:', b'601.03', b'Mbit/s', '2026-02-17 08:38:57']
Test number: 99
[b'Ping:', b'14.493', b'ms', b'Download:', b'2212.29', b'Mbit/s', b'Upload:', b'658.22', b'Mbit/s', '2026-02-17 08:39:02']

## Part 2: Manipulate Data

The Python library `pandas` is very useful for working with structured data. The full documentation can be found here: http://pandas.pydata.org/pandas-docs/version/0.14.1/</font>

A larger dataset collected in advance will be used for this part of the lab. The filename is `rpi_data_long.csv`.

#### Step 1: Import the Python libraries.

Import `pandas` and the other libraries used for the next tasks.

In [29]:
# Code cell 19
import datetime
import csv
import pandas as pd
# NumPy is a library that adds support for large, multi-dimensional arrays and matrices
# along with high-level mathematical functions to operate on these arrays
import numpy as np

#### Step 2: Load the `csv` file into a `DataFrame` object using `pandas`.

A `pandas DataFrame` is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table. The pandas library function `read_csv` automatically converts a `csv` file into a `DataFrame` object.

Read the `read_csv` documentation in http://pandas.pydata.org/pandas-docs/version/0.14.1/generated/pandas.read_csv.html.
This function contains a lot of parameters. The only non-optional one is the `filepath`, i.e. the location of the `csv` file. All the other parameters are optional.

In this step, you will import and view the content of the csv file, `rpi_data_long.csv`. This csv file is located in the same directory as this Jupyter notebook.

a) Assign the file `rpi_data_long.csv` to the variable `data_file`.

In [30]:
# Code cell 20
data_file = './rpi_data_long.csv'

b) Use the Linux command `head` to view the first 10 lines of the csv file.

In [31]:
# Code cell 21
!head -n 5 ./rpi_data_long.csv

b'Ping:',b'21.661',b'ms',b'Download:',b'2469.13',b'Mbit/s',b'Upload:',b'552.68',b'Mbit/s',2026-02-17 08:26:22
b'Ping:',b'13.242',b'ms',b'Download:',b'2603.62',b'Mbit/s',b'Upload:',b'558.49',b'Mbit/s',2026-02-17 08:26:27
b'Ping:',b'13.139',b'ms',b'Download:',b'2263.88',b'Mbit/s',b'Upload:',b'635.75',b'Mbit/s',2026-02-17 08:26:32
b'Ping:',b'13.3',b'ms',b'Download:',b'2344.32',b'Mbit/s',b'Upload:',b'618.81',b'Mbit/s',2026-02-17 08:26:36
b'Ping:',b'13.04',b'ms',b'Download:',b'2883.40',b'Mbit/s',b'Upload:',b'558.77',b'Mbit/s',2026-02-17 08:26:41

c) Use the `names` parameter of the `read_csv` function to specify the name of the `DataFrame` columns.

In [32]:
# Code cell 22
column_names = [ 'Type A', 'Measure A', 'Units A',
                 'Type B', 'Measure B', 'Units B',
                 'Type C', 'Measure C', 'Units C',
                 'Datetime']

d) Use the `read_csv` function to read from `data_file` and assign `column_names` as the column names in the dataframe.

In [33]:
# Code cell 23
with open(data_file, 'r') as f:
    df_redundant = pd.read_csv(f, names = column_names)

e) The command `head()` displays the first few rows of the dataframe.

In [35]:
# Code cell 24
# You can specify the number of rows you want to print to screen:
# you do so passing the number as an argument to the function
# (e.g., head(10))
df_redundant.head(20)

,Type A,Measure A,Units A,Type B,Measure B,Units B,Type C,Measure C,Units C,Datetime
0,b'Ping:',b'21.661',b'ms',b'Download:',b'2469.13',b'Mbit/s',b'Upload:',b'552.68',b'Mbit/s',2026-02-17 08:26:22
1,b'Ping:',b'13.242',b'ms',b'Download:',b'2603.62',b'Mbit/s',b'Upload:',b'558.49',b'Mbit/s',2026-02-17 08:26:27
2,b'Ping:',b'13.139',b'ms',b'Download:',b'2263.88',b'Mbit/s',b'Upload:',b'635.75',b'Mbit/s',2026-02-17 08:26:32
3,b'Ping:',b'13.3',b'ms',b'Download:',b'2344.32',b'Mbit/s',b'Upload:',b'618.81',b'Mbit/s',2026-02-17 08:26:36
4,b'Ping:',b'13.04',b'ms',b'Download:',b'2883.40',b'Mbit/s',b'Upload:',b'558.77',b'Mbit/s',2026-02-17 08:26:41
5,b'Ping:',b'13.02',b'ms',b'Download:',b'2552.66',b'Mbit/s',b'Upload:',b'646.07',b'Mbit/s',2026-02-17 08:26:46
6,b'Ping:',b'13.044',b'ms',b'Download:',b'2360.04',b'Mbit/s',b'Upload:',b'630.02',b'Mbit/s',2026-02-17 08:26:50
7,b'Ping:',b'13.107',b'ms',b'Download:',b'2329.67',b'Mbit/s',b'Upload:',b'642.47',b'Mbit/s',2026-02-17 08:26:55
8,b'Ping:',b'13.148',b'ms',b'Download:',b'2217.74',b'Mbit/s',b'Upload:',b'572.83',b'Mbit/s',2026-02-17 08:27:00
9,b'Ping:',b'13.162',b'ms',b'Download:',b'3424.87',b'Mbit/s',b'Upload:',b'729.07',b'Mbit/s',2026-02-17 08:27:05
10,b'Ping:',b'13.388',b'ms',b'Download:',b'2366.15',b'Mbit/s',b'Upload:',b'650.85',b'Mbit/s',2026-02-17 08:27:09
11,b'Ping:',b'13.312',b'ms',b'Download:',b'2351.31',b'Mbit/s',b'Upload:',b'571.26',b'Mbit/s',2026-02-17 08:27:14
12,b'Ping:',b'13.182',b'ms',b'Download:',b'3504.12',b'Mbit/s',b'Upload:',b'644.38',b'Mbit/s',2026-02-17 08:27:19
13,b'Ping:',b'13.105',b'ms',b'Download:',b'2326.49',b'Mbit/s',b'Upload:',b'652.45',b'Mbit/s',2026-02-17 08:27:23
14,b'Ping:',b'13.078',b'ms',b'Download:',b'2224.50',b'Mbit/s',b'Upload:',b'675.33',b'Mbit/s',2026-02-17 08:27:28
15,b'Ping:',b'13.032',b'ms',b'Download:',b'3095.19',b'Mbit/s',b'Upload:',b'571.77',b'Mbit/s',2026-02-17 08:27:32
16,b'Ping:',b'13.062',b'ms',b'Download:',b'2208.34',b'Mbit/s',b'Upload:',b'621.78',b'Mbit/s',2026-02-17 08:27:37
17,b'Ping:',b'13.403',b'ms',b'Download:',b'2305.52',b'Mbit/s',b'Upload:',b'688.75',b'Mbit/s',2026-02-17 08:27:42
18,b'Ping:',b'12.813',b'ms',b'Download:',b'3169.05',b'Mbit/s',b'Upload:',b'546.21',b'Mbit/s',2026-02-17 08:27:47
19,b'Ping:',b'13.095',b'ms',b'Download:',b'2328.07',b'Mbit/s',b'Upload:',b'708.55',b'Mbit/s',2026-02-17 08:27:51

What is the code to read the first 20 lines of the csv file?

Нужно указать нужное количество строк в значении `head(N)`

#### Step 3: Create a concise representation.
In this step, you will create a more compact representation using a copy of the data frame `df_redundant`.

a) Copy `df_redundant` into another dataframe called `df_compact` using `copy()`.

In [36]:
# Code cell 25
df_compact = df_redundant.copy()

b) Rename the columns relative to the measures as shown:

    Measure A -> Ping (ms)
    Measure B -> Download (Mbit/s)
    Measure C -> Upload (Mbit/s)

In [37]:
# Code cell 26
df_compact.rename(columns={'Measure A':'Ping (ms)',
                           'Measure B': 'Download (Mbit/s)',
                           'Measure C': 'Upload (Mbit/s)'}, inplace=True)
df_compact.head(3)

,Type A,Ping (ms),Units A,Type B,Download (Mbit/s),Units B,Type C,Upload (Mbit/s),Units C,Datetime
0,b'Ping:',b'21.661',b'ms',b'Download:',b'2469.13',b'Mbit/s',b'Upload:',b'552.68',b'Mbit/s',2026-02-17 08:26:22
1,b'Ping:',b'13.242',b'ms',b'Download:',b'2603.62',b'Mbit/s',b'Upload:',b'558.49',b'Mbit/s',2026-02-17 08:26:27
2,b'Ping:',b'13.139',b'ms',b'Download:',b'2263.88',b'Mbit/s',b'Upload:',b'635.75',b'Mbit/s',2026-02-17 08:26:32

c) Because the Types and Units columns are no longer necessary, these columns can be dropped.

In [38]:
# Code cell 27
df_compact.drop(['Type A', 'Type B', 'Type C',
         'Units A', 'Units B', 'Units C'], axis=1, inplace=True)
df_compact.head()

   Ping (ms) Download (Mbit/s) Upload (Mbit/s)             Datetime
0  b'21.661'        b'2469.13'       b'552.68'  2026-02-17 08:26:22
1  b'13.242'        b'2603.62'       b'558.49'  2026-02-17 08:26:27
2  b'13.139'        b'2263.88'       b'635.75'  2026-02-17 08:26:32
3    b'13.3'        b'2344.32'       b'618.81'  2026-02-17 08:26:36
4   b'13.04'        b'2883.40'       b'558.77'  2026-02-17 08:26:41

In the table above, the `Datetime` field is a string. Pandas and Python offer a number of operations to work with date and time that can be very helpful.

In the next step, the string in the `Datetime` column will be separated into two new columns.

#### Step 4: Separate data into two columns.
In this step, you will use Pandas to generate the columns `Date` and `Time` from the column `Datetime` and then drop the `Datetime` column.
<p>The `lambda` function is used create two anonymous functions that extract only the date and the time from a `datetime` object, respectively. Then, use the `pandas` function `apply` to apply this function to an entire column (in practice, `apply` implicitly defines a `for` loop and passes the rows one by one to our `lambda` function). Store the result of the `apply` functions in two new columns of the `DataFrame`.

a) Apply the `lambda` function to iterate through the data frame to split the date from the `Datetime` column.

In [39]:
# Code cell 28
df_compact['Date'] = df_compact['Datetime'].apply(lambda dt_str: pd.to_datetime(dt_str).date())

b) Repeat step a to split time from `Datetime` column.

In [40]:
# Code cell 29
# Please note, this requires an intermediate step, because of how NaT are treated by the time() function.
# Reference: https://github.com/pandas-dev/pandas/issues/11453
temp = df_compact['Datetime'].apply(lambda dt_str: pd.to_datetime(dt_str))
df_compact['Time'] = temp.dt.time

c) All the information for the `Datetime` column has now been copied to the `Date` and `Time` columnns. The `Datetime` column serves no purpose. The `Datetime` column can be dropped from the data frame.
<p>Enter the code to drop the `Datetime` column in the cell below.

In [41]:
# Code cell 30
df_compact.drop(['Datetime'], axis=1, inplace=True)

Enter the code to print out the first 3 rows of the data frame to verify the changes.

In [42]:
# Code cell 31
df_compact.head(3)

   Ping (ms) Download (Mbit/s) Upload (Mbit/s)        Date      Time
0  b'21.661'        b'2469.13'       b'552.68'  2026-02-17  08:26:22
1  b'13.242'        b'2603.62'       b'558.49'  2026-02-17  08:26:27
2  b'13.139'        b'2263.88'       b'635.75'  2026-02-17  08:26:32

d) Use the `type` function to print out the variable type of the values in the `Date` and `Time` columns.

In [43]:
# Code cell 32
print(df_compact['Date'][0], type(df_compact['Date'][0]) )
print(df_compact['Time'][0], type(df_compact['Time'][0]) )

2026-02-17 <class 'datetime.date'>
08:26:22 <class 'datetime.time'>

#### Step 5: Save the new data frame.
Save the pandas dataframe `df_compact` as a csv file called `rpi_data_compact`:

In [45]:
# Code cell 33
df_compact.to_csv('./rpi_data_compact.csv')

<font size='0.5'>&copy; 2017 Cisco and/or its affiliates. All rights reserved. This document is Cisco Public.<font>

# Ответы на контрольные вопросы

**1. Что такое анонимная функция Python, как она работает?**

Lambda - это анонимная функция в Python, предназначена для быстрого создания небольших функций на месте, которые обычно состоят из одного выражения

**2. Что возвращает функция speedtest ()? Какой код используется для просмотра результатов функции speedtest ()?**

Функция `speedtest()` возвращает список, содержащий результаты измерения скорости (ping, скорость загрузки, скорость выгрузки) и метку времени, когда был выполнен тест.

Для просмотра результатов можно вызвать функцию и распечатать её вывод с помощью `print`

**3. Каким образом выполняется переименование столбцов датафрейма?**

Для переименования мы используем метод `rename`, пример переименования представлен в "Code cell 26":

```
df_compact.rename(columns={'Measure A':'Ping (ms)',
                           'Measure B': 'Download (Mbit/s)',
                           'Measure C': 'Upload (Mbit/s)'}, inplace=True)
```

`inplace=True` означает, что мы не создаем новый список, а переименовываем уже имеющийся

**4. Для чего в лабораторной работе импортируется библиотека NumPy?**

В данной лабораторной работе библиотека NumPy импортируется для поддержки библиотеки Pandas

**5. Как выглядит код удаления столбца Datetime?**

Код для удаления столбца Datetime выглядит следующим образом и представлен в ячейке "Code cell 30":

```
df_compact.drop(['Datetime'], axis=1, inplace=True)
```